apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
data:
  APP_NAME: Laravel
  APP_ENV: production
  APP_DEBUG: "true"
  APP_TIMEZONE: UTC
  APP_URL: https://{{ .Values.host.domain }}/
  ASSET_URL: https://{{ .Values.host.domain }}/
  APP_LOCALE: en
  APP_FALLBACK_LOCALE: en
  APP_FAKER_LOCALE: en_US
  APP_MAINTENANCE_DRIVER: file
  DB_CONNECTION: mysql
  DB_HOST: argocd-laravel-mysql-sc-3f83.d.aivencloud.com
  DB_PORT: "11386"
  DB_DATABASE: defaultdb
  DB_USERNAME: avnadmin