apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-laravel-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-laravel-application
  template:
    metadata:
      labels:
        app: argocd-laravel-application
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
    spec:
      volumes:
        - name: logs
          emptyDir: {}
        - name: views
          emptyDir: {}
      securityContext:
        fsGroup: 82
      initContainers:
        - name: database-migrations
          image: registry.digitalocean.com/kukiamarilla-registry/argocd-laravel-app-backend:{{ .Values.env.APP_VERSION }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-secret
      containers:
        - name: nginx
          imagePullPolicy: IfNotPresent
          image: registry.digitalocean.com/kukiamarilla-registry/argocd-laravel-app-frontend:{{ .Values.env.APP_VERSION }}
          resources: {}
            # limits:
            #   cpu: 500m
            #   memory: 50M
          ports:
            - containerPort: 80
        - name: fpm
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-secret
          securityContext:
            runAsUser: 82
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/storage/logs
            - name: views
              mountPath: /var/www/html/storage/framework/views
          resources: {}
          image: registry.digitalocean.com/kukiamarilla-registry/argocd-laravel-app-backend:{{ .Values.env.APP_VERSION }}
          ports:
            - containerPort: 9000