apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravel-ingress
  namespace: app
spec:
  ingressClassName: nginx
  rules:
  - host: 146.190.196.197.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-laravel-svc
            port:
              number: 80