apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
type: Opaque
data:
  APP_KEY: YmFzZTY0OkMzQ3F1Tk9XZ1kxQ2RWcnVFcWlUeGdEOFFQZWRSRUpEVGh5Vyt6MXVvVW89
  DB_PASSWORD: QVZOU19WdkFjTHFmbUMxTURjSmNUSUZn