apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-laravel-svc
  name: argocd-laravel-svc
spec:
  type: NodePort
  selector:
    app: argocd-laravel-application
  ports:
  - name: targetport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007